### ISSUE TITLE
Where can I see whole palette

### ISSUE THREAD

**Issue by crystalball808** [ramojus/mellifluous.nvim#11]
Hello
I want to add colorschemes for iTerm and Zellij and I need a color palette for this
Can you please provide a representation in a JSON or something

**Comment by ramojus** [comment]
Hi,
I'm not against this, but I feel like manually creating colorschemes for each terminal shouldn't be the way here. Why has no one created a plugin yet that just takes `vim.g.terminal_color_x` color values on command and outputs them in any terminal format? Or maybe I just can't find it.
Anyways, I think you should use `vim.g.terminal_color_x` colors, not the ones that are used for highlighting code, as `vim.g.terminal_color_x` colors should be more balanced. Also, this colorscheme doesn't have all of the terminal colors (no cyan), so with the default color set it currently looks like this:
![image](https://github.com/ramojus/mellifluous.nvim/assets/41536253/c7032f03-5ecc-4e00-a1c3-8d07511e807b)

If you want to proceed, here are the colors for dark variant:
```
color0: #1a1a1a
color1: #d59192
color2: #b3b393
color3: #bfaf8e
color4: #a8a1be
color5: #b99bb5
color6: #a8a1be
color7: #5b5b5b
color8: #242424
color9: #ffbcbd
color10: #dfdfbe
color11: #ecdbb9
color12: #d4cdeb
color13: #e6c6e1
color14: #d4cdeb
color15: #aeaeae
```
and colors for light variant:
```
color0: #e7e7e7
color1: #b73242
color2: #63611e
color3: #9c792a
color4: #5a418a
color5: #863e7f
color6: #5a418a
color7: #919191
color8: #f2f2f2
color9: #e8606a
color10: #8b8a49
color11: #c8a357
color12: #826ab6
color13: #b267aa
color14: #826ab6
color15: #414141
```

**Comment by crystalball808** [comment]
Thank you
