### ISSUE TITLE
Terminal emulator ports

### ISSUE THREAD

**Issue by serhez** [ramojus/mellifluous.nvim#19]
Are there any terminal emulator ports of this colorscheme (e.g., wezterm, kitty, alacritty)? Thanks!

**Comment by ramojus** [comment]
There aren't any terminal ports. Instead I have plans to create a plugin that exports current neovim terminal colors to some terminal config syntax, but I'm not there yet, and will not be for a while.

You can find the palette here: https://github.com/ramojus/mellifluous.nvim/issues/11#issuecomment-1872490332
