### ISSUE TITLE
Various columns

### ISSUE THREAD

**Issue by windowsrefund** [ramojus/mellifluous.nvim#22]
Hello again,

Thank you for the help with #21. I've been migrating my configuration to AstroNvim v4 which is giving me an opportunity to see things I've traditionally disabled and/or never bothered to use. In addition to our number column, the following image shows an active _foldcolumn_ and _signcolumn_. Do these look right?

![cols](https://github.com/ramojus/mellifluous.nvim/assets/512222/ff8a11d1-354e-4e42-b20c-984356cfb178)

**Comment by ramojus** [comment]
Hi,
No, the `FoldColumn` would look much better if it linked to `LineNr` highlight, I think. I will update the `FoldColumn` highlight.
How did you get the signcolumn to be before the number column? I wasn't aware that it's possible. Totally messes up the `CursorLineNr` highlight. Something should be done about this as well.

**Comment by ramojus** [comment]
signcolumn is on the other side of number column for me:
![image](https://github.com/ramojus/mellifluous.nvim/assets/41536253/929ec5d0-226d-4851-aee8-c2ca91be7b2f)
I couldn't find any option that could be related

**Comment by windowsrefund** [comment]
I don't know as it's provided via Astronvim. I'll see if it I can dig in and grok how they do it.

**Comment by windowsrefund** [comment]
I couldn't find anything obvious in the astronvim repos. This makes sense actually since all we're talking about is the scenario where _vim.opt.signcolumn_ is set to _yes_, _no_, or _auto_. In other words, a distro like AstroNvim wouldn't be responsible for rendering it this or that way. That's got me thinking it must be related to the version of nvim we're running? I happen to be on v0.9.5

**Comment by ramojus** [comment]
I got it. It must have something to do with `statuscolumn` option. You can heavily customize your columns with this option. With that in mind, I don't think I'll try to account for every possible customization in default highlights/config of the colorscheme. So I would recommend either not using `statuscolumn` or this mellifluous config:
```lua
flat_background = {
    cursor_line_number = true,
},
```

**Comment by ramojus** [comment]
This is where they do it astronvim: https://github.com/AstroNvim/AstroNvim/blob/7aa58a758eb6f662f5ca4fc1a94152e29e0bc758/lua/astronvim/plugins/heirline.lua#L117

**Comment by windowsrefund** [comment]
Very interesting. I will play with this tonight. Thank you.
