### ISSUE TITLE
Bro i am having trouble installing it....

### ISSUE THREAD

**Issue by ncorbuk** [ramojus/mellifluous.nvim#38]
I am using https://github.com/junegunn/vim-plug i am getting an error when i go to change to the colorscheme 
![Screenshot from 2024-05-29 23-32-00](https://github.com/ramojus/mellifluous.nvim/assets/44022617/01aeec05-5c8e-4fb7-8bf8-91a34edc4365)

**Comment by windowsrefund** [comment]
pro tip: Stop using screenshots to convey text.

**Comment by antoineco** [comment]
Maybe your Neovim is outdated? Would you be able to install either 0.9 or 0.10?

**Comment by ramojus** [comment]
Closing as there is a seemingly correct answer given and no response
