### ISSUE TITLE
Lazy does not honor transparent_background settings

### ISSUE THREAD

**Issue by antoineco** [ramojus/mellifluous.nvim#51]
`LazyNormal` is currently ignoring transparency settings for floating windows:

<img width="1113" alt="Screenshot 2024-07-30 at 14 20 03" src="https://github.com/user-attachments/assets/e4d703cc-addb-4cc3-8ceb-37ebca37dfd3">

I submitted a proposal for a fix in #49 with screenshots showing the expected result with different combinations of settings.
I closed that PR because it seems unlikely that the approach will be considered, but feel free to source inspiration from the details it contains.

**Comment by ramojus** [comment]
Thanks for noticing the issue!
