### ISSUE TITLE
`config` table resets but not the `are_color_set_defaults_merged` flag  if `apply` is called the second time

### ISSUE THREAD

**Issue by TinusgragLin** [ramojus/mellifluous.nvim#54]
Hi, I just hit this minor bug where doing `colorscheme mellifluous` twice would result in a nil value indexing error.

After some digging, the cause seems to be that every time we call `apply` (and thus `load`, `config.prepare`), the local variable `config` in module `config` is reset to the default value, but the flag `are_color_set_defaults_merged` still retains the value `true` after the last `apply`, so the default color set configs are not merged to `config`, resulting in a nil value indexing error at later time.

Should we keep the `config` resetting behavior and simply do the merge every time or have a similar flag `are_config_initialized`?

**Comment by ramojus** [comment]
I've managed to replicate and then fixed the issue, so it should work now. I've decided to remerge every time. Thanks for investigating this!
