### ISSUE TITLE
Background color is off after switching between light and dark modes (v1 branch)

### ISSUE THREAD

**Issue by antoineco** [ramojus/mellifluous.nvim#61]
While playing around with the `v1` branch, I noticed that switching between dark and light modes was now causing the background color to change.

I have overridden the background color as suggested in the wiki, along with a couple of foreground color overrides (ref. https://github.com/ramojus/mellifluous.nvim/discussions/41):

```lua
  {
    "ramojus/mellifluous.nvim",
    branch = "v1",
    lazy = false,
    priority = 1000,
    opts = {
      mellifluous = {
        color_overrides = {
          dark = {
            bg = function(bg)
              return bg:lightened(2)  -- soft contrast
            end,
            colors = function(colors)
              return {
                fg = colors.fg:darkened(7),
                shades_fg = colors.fg
              }
            end
          },
          light = {
            bg = function(bg)
              return bg:lightened(2)  -- hard contrast
            end
          }
        }
      }
    }
  }
}
```

Upon opening Neovim, everything is initially fine:

```
=require'mellifluous.colors'.get_colors().bg
{
  hex = "#1f1f1f",
```

However, the next switch from light to dark causes the background color to be permanently altered:

```
=require'mellifluous.colors'.get_colors().bg
{
  hex = "#231d1d",
```

I used the term "permanently" because the background color remains `#231d1d` no matter how many times I switch between light and dark modes, but it never returns to `#1f1f1f`.

**Comment by ramojus** [comment]
Thanks for checking v1. Does #62 fix your issue?

**Comment by antoineco** [comment]
@ramojus it does, thanks!
